// Copyright (c) 2026 BEL ESPRIT D ACCORD TRUST HOLDINGS INC. All rights reserved.
// Patent Pending.
//
// sha256_csa.rs — Corrected Rust sha256_carry_matrix (CSA trace)
// --------------------------------------------------------------------
// Source: Ahmad's 2026-08-29 wiring spec — corrected artifact shape.
// This replaces the earlier ambiguous (b,cin,out) CarryTuple with a
// proper 3-input CSA row: three same-column inputs x,y,z → sum, carry.
// Mirrors Lean lean/SHA256CarryMatrix.lean:
//
//   Rust columns[i].x ↔ (m i).x
//   Rust columns[i].y ↔ (m i).y
//   Rust columns[i].z ↔ (m i).z
//   Rust columns[i].sum ↔ faSum (m i).x (m i).y (m i).z = x⊕y⊕z
//   Rust columns[i].carry ↔ faCarry (m i).x (m i).y (m i).z = Maj
//
// Ch(e,f,g) and Maj(a,b,c) are Boolean-word addends; CSA carry rows are
// generated only when reducing arithmetic addends for T1/T2/CPA.
//
// Honest scope: proves the CSA identity X+Y+Z = S + 2·C (unshifted C bits)
// and modulo 2^32 via wrapping_add. Does NOT prove SHA-256 preimage break.

/// CSA row: three same-column bits → sum + unshifted carry
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CsaColumn {
    pub x: bool,
    pub y: bool,
    pub z: bool,
    pub sum: bool,
    pub carry: bool,
}

/// CSA layer: one 3-input reduction, 32 columns, sum + carry words
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CsaLayer {
    pub inputs: [u32; 3],
    pub sum: u32,
    /// Unshifted: bit i is carry generated by column i.
    pub carry_bits: u32,
    /// Shifted carry contribution (carry_bits << 1) to next column.
    pub carry: u32,
    pub columns: [CsaColumn; 32],
}

const ZERO_COLUMN: CsaColumn = CsaColumn {
    x: false,
    y: false,
    z: false,
    sum: false,
    carry: false,
};

/// Build one CSA layer from three words.
/// Lean: faSum = x⊕y⊕z, faCarry = Maj = (x∧y)∨(x∧z)∨(y∧z)
pub fn csa_layer(x: u32, y: u32, z: u32) -> CsaLayer {
    let mut columns = [ZERO_COLUMN; 32];
    let mut sum = 0_u32;
    let mut carry_bits = 0_u32;
    for i in 0..32 {
        let xi = ((x >> i) & 1) != 0;
        let yi = ((y >> i) & 1) != 0;
        let zi = ((z >> i) & 1) != 0;
        let sum_i = xi ^ yi ^ zi;
        let carry_i = (xi & yi) | (xi & zi) | (yi & zi);
        columns[i] = CsaColumn { x: xi, y: yi, z: zi, sum: sum_i, carry: carry_i };
        sum |= (sum_i as u32) << i;
        carry_bits |= (carry_i as u32) << i;
        debug_assert_eq!((xi as u8) + (yi as u8) + (zi as u8), (sum_i as u8) + 2 * (carry_i as u8));
    }
    CsaLayer {
        inputs: [x, y, z],
        sum,
        carry_bits,
        carry: carry_bits << 1,
        columns,
    }
}

/// Verify CSA layer exactly: X+Y+Z = S + 2·C (unshifted) and mod 2^32
pub fn verify_csa_layer(layer: &CsaLayer) {
    let [x, y, z] = layer.inputs;
    let lhs = x as u64 + y as u64 + z as u64;
    let rhs = layer.sum as u64 + ((layer.carry_bits as u64) << 1);
    assert_eq!(lhs, rhs, "exact CSA identity failed: {}+{}+{} != {}+2*{}", x, y, z, layer.sum, layer.carry_bits);
    assert_eq!(
        x.wrapping_add(y).wrapping_add(z),
        layer.sum.wrapping_add(layer.carry),
        "mod-2^32 CSA identity failed"
    );
    for (i, col) in layer.columns.iter().enumerate() {
        let xi = ((x >> i) & 1) != 0;
        let yi = ((y >> i) & 1) != 0;
        let zi = ((z >> i) & 1) != 0;
        assert_eq!((col.x, col.y, col.z), (xi, yi, zi));
        assert_eq!(col.sum, xi ^ yi ^ zi);
        assert_eq!(col.carry, (xi & yi) | (xi & zi) | (yi & zi));
    }
}

// ---------------------------------------------------------------------------
// SHA-256 Boolean functions (addends)
// ---------------------------------------------------------------------------

pub fn ch(e: u32, f: u32, g: u32) -> u32 {
    (e & f) ^ ((!e) & g)
}

pub fn maj(a: u32, b: u32, c: u32) -> u32 {
    (a & b) ^ (a & c) ^ (b & c)
}

pub fn big_sigma0(a: u32) -> u32 {
    a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22)
}

pub fn big_sigma1(e: u32) -> u32 {
    e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25)
}

// ---------------------------------------------------------------------------
// T1 composition: 5 addends via 3 CSA layers + final CPA
// T1 = h + Σ1(e) + Ch(e,f,g) + Kt + Wt  (mod 2^32)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct T1Trace {
    pub h: u32,
    pub sigma1_e: u32,
    pub ch_efg: u32,
    pub k_t: u32,
    pub w_t: u32,
    pub layer0: CsaLayer, // [h, Σ1(e), Ch]
    pub layer1: CsaLayer, // [carry0, Kt, Wt]
    pub layer2: CsaLayer, // [sum0, sum1, carry1]
    pub final_sum: u32,
    pub expected: u32,
}

pub fn t1_via_csa(h: u32, e: u32, f: u32, g: u32, k_t: u32, w_t: u32) -> T1Trace {
    let sigma1_e = big_sigma1(e);
    let ch_efg = ch(e, f, g);
    let layer0 = csa_layer(h, sigma1_e, ch_efg);
    let layer1 = csa_layer(layer0.carry, k_t, w_t);
    let layer2 = csa_layer(layer0.sum, layer1.sum, layer1.carry);
    let final_sum = layer2.sum.wrapping_add(layer2.carry);
    let expected = h.wrapping_add(sigma1_e).wrapping_add(ch_efg).wrapping_add(k_t).wrapping_add(w_t);
    assert_eq!(final_sum, expected, "T1 CSA final sum mismatch");
    // Each layer preserves weighted_rows_sum (Lean)
    verify_csa_layer(&layer0);
    verify_csa_layer(&layer1);
    verify_csa_layer(&layer2);
    T1Trace { h, sigma1_e, ch_efg, k_t, w_t, layer0, layer1, layer2, final_sum, expected }
}

// ---------------------------------------------------------------------------
// T2 composition: 2 addends (no CSA needed, but provide uniform 3-input)
// T2 = Σ0(a) + Maj(a,b,c)
// ---------------------------------------------------------------------------

pub fn t2(a: u32, b: u32, c: u32) -> u32 {
    big_sigma0(a).wrapping_add(maj(a, b, c))
}

pub fn t2_via_csa(a: u32, b: u32, c: u32) -> (CsaLayer, u32) {
    let sigma0_a = big_sigma0(a);
    let maj_abc = maj(a, b, c);
    let layer = csa_layer(sigma0_a, maj_abc, 0);
    let result = layer.sum.wrapping_add(layer.carry);
    assert_eq!(result, sigma0_a.wrapping_add(maj_abc));
    verify_csa_layer(&layer);
    (layer, result)
}

// ---------------------------------------------------------------------------
// Trace hierarchy (separates Boolean addends from CSA carries)
// ---------------------------------------------------------------------------

pub struct Sha256RoundMatrix {
    pub round_idx: usize,
    pub ch_efg: u32,
    pub maj_abc: u32,
    pub t1: T1Trace,
    pub t2_csa: CsaLayer,
    pub t2: u32,
    pub new_a: u32,
    pub new_e: u32,
}

pub fn sha256_round_matrix(
    round_idx: usize,
    a: u32, b: u32, c: u32, d: u32,
    e: u32, f: u32, g: u32, h: u32,
    k_t: u32, w_t: u32,
) -> Sha256RoundMatrix {
    let ch_efg = ch(e, f, g);
    let maj_abc = maj(a, b, c);
    let t1 = t1_via_csa(h, e, f, g, k_t, w_t);
    let (t2_csa, t2_val) = t2_via_csa(a, b, c);
    let new_a = t1.final_sum.wrapping_add(t2_val);
    let new_e = d.wrapping_add(t1.final_sum);
    Sha256RoundMatrix { round_idx, ch_efg, maj_abc, t1, t2_csa, t2: t2_val, new_a, new_e }
}

// ---------------------------------------------------------------------------
// Lean-bridge serialization (Rust provides data, Lean checks derivation)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct LeanCsaColumn {
    pub bit: u8,
    pub x: bool,
    pub y: bool,
    pub z: bool,
}

#[derive(Debug, Clone)]
pub struct LeanCsaMatrix {
    pub width: usize, // 32
    pub columns: Vec<LeanCsaColumn>,
}

impl From<&CsaLayer> for LeanCsaMatrix {
    fn from(layer: &CsaLayer) -> Self {
        let columns = layer.columns.iter().enumerate().map(|(i, col)| LeanCsaColumn {
            bit: i as u8, x: col.x, y: col.y, z: col.z,
        }).collect();
        LeanCsaMatrix { width: 32, columns }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_csa_identity_random() {
        for (x, y, z) in [(0u32, 0, 0), (!0, 0, 0), (12345, 67890, 13579), (!0, !0, !0)] {
            let layer = csa_layer(x, y, z);
            verify_csa_layer(&layer);
        }
    }

    #[test]
    fn test_t1_via_csa_matches_wrapping() {
        let t1 = t1_via_csa(0x6a09e667, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x428a2f98, 0xe9b5dba5);
        assert_eq!(t1.final_sum, t1.expected);
    }

    #[test]
    fn test_t2_via_csa_matches() {
        let a = 0x6a09e667; let b = 0xbb67ae85; let c = 0x3c6ef372;
        let (layer, t2_val) = t2_via_csa(a, b, c);
        assert_eq!(t2_val, t2(a, b, c));
        assert_eq!(layer.inputs[2], 0);
    }

    #[test]
    fn test_sha256_round_matrix_no_panic() {
        let m = sha256_round_matrix(0, 0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19, 0x428a2f98, 0xe9b5dba5);
        assert_eq!(m.ch_efg, ch(0x510e527f, 0x9b05688c, 0x1f83d9ab));
        assert_eq!(m.maj_abc, maj(0x6a09e667, 0xbb67ae85, 0x3c6ef372));
    }
}
